\section{Contrasts}
The \code{yates} function does simple and population contrasts.
The key arguments are fit, estimate and population.
A faily standard call
<<yates>>=
yates <- function(fit, estimate, population='none', method) {
    beta <- coef(fit)  
    var  <- vcov(fit)
    Terms <- terms(fit)
    assign <- fit$assign
    xlevels <- fit$xlevels

    if (!is.list(estimate)) stop("the estimate argument must be a list")
    
    
